server:
  port: 8666
spring:
  datasource:
    url: jdbc:postgresql://localhost:54342/webauth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

        default_schema: public


  flyway:
    baseline-on-migrate: true
    locations: classpath:src/main/resources/db/migration

    create-schemas: false
    init-sql: CREATE IF NOT EXISTS flyway_history_schema
    schemas: flyway_history_schema,public
    user: postgres
    password: postgres
    default-schema: public

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 178882648011-9ah79uc68ha8bhtvmk2hkg0jvpfpm4or.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
